# Generated by Django 4.2.1 on 2023-05-11 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appeal",
            options={
                "verbose_name": "Связаться с нами",
                "verbose_name_plural": "Связаться с нами",
            },
        ),
    ]
